version: '3'
services:
  web:
    build: ./app
    volumes:
      - ./app/:/app
      - /app/vendor/bundle
    ports:
      - "4567:4567"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - MYSQL_DATABASE=mumu_labo_dev
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  db:
    image: mysql:8.0
    volumes:
      - .:/app
      - mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
volumes:
  mysql-data: