# frozen_string_literal: true

source 'https://rubygems.org'

gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'

group :development do
  gem 'rubocop'
end

group :test do
  gem 'rack-test'
  gem 'rspec'
end
